### ISSUE TITLE
Issue in running_sql_queries_on_dataframes.Rmd

### ISSUE THREAD

**Issue by Gangadharareddy514** [jtr13/cc21fall2#166]
Hi Professor @jtr13,
There is an issue in this, could you please help me out.
https://github.com/jtr13/cc21fall2/actions/runs/1446360938
There is an error in this function-> fun(environment()) : invalid first argument

**Comment by jtr13** [comment]
That run doesn't exist anymore for some reason but it's still failing for the same reason. It's the same problem as with the Python chapters; we don't have SQL installed so it can't execute the SQL chunks. I set `eval=FALSE` which we can change if we're able to solve it.

**Comment by jtr13** [comment]
Original pull request: https://github.com/jtr13/cc21fall2/pull/6 @ksdkalluri

**Comment by HannahFromAland** [comment]
The page `running_sql_queries_on_dataframes.Rmd` caused another error `Error: external pointer is not valid` this morning. https://github.com/jtr13/cc21fall2/actions/runs/1456643849
I set `cache = FALSE` with reference to this same error :https://github.com/Bioconductor/BiocWorkshops/issues/32 
And now it's working :)

**Comment by jtr13** [comment]
Fantastic!

**Comment by HannahFromAland** [comment]
Seems I spoke a little too soon....It began to fail again 🥲 https://github.com/jtr13/cc21fall2/actions/runs/1456742319

**Comment by jtr13** [comment]
This is a tough one. In general it's not completely clear how the Rmarkdown cache works. In addition, `eval=FALSE` doesn't work the same way for SQL, see here: https://community.rstudio.com/t/using-eval-f-in-sql-code-block-in-rmarkdown/83960. I just changed all the SQL chunks to \`\`\`sql so it won't try at all to execute them. We'll see if it works. 🤞

**Comment by jtr13** [comment]
Failed again 😢   It's getting stuck on an R chunk even though `eval=FALSE` for all chunks. It's possible that the setup chunk that includes `cache=FALSE` is actually cached and preventing `eval=FALSE` from being implemented. I tried moving it we'll see what happens. What's really strange is that this chapter has rendered on some runs.

**Comment by jtr13** [comment]
Woohoo, that worked... we'll see how long it lasts.

**Comment by ksdkalluri** [comment]
Sorry, I didn't get to look at this earlier, is there anything I could do to help fix the issue?
