### ISSUE TITLE
Issue on run #204

### ISSUE THREAD

**Issue by nicric99** [jtr13/cc21fall2#168]
quitting from lines 45-49 (running_sql_queries_on_dataframes.Rmd) 
Error: Error in fun(environment()) : invalid first argument
Calls: local ... call_block -> <Anonymous> -> lazyLoad -> lazyLoadDBexec -> fun
Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
 Failed to compile running_sql_queries_on_dataframes.Rmd
Calls: <Anonymous> -> render_new_session -> Rscript_render
Execution halted
Error: Process completed with exit code 1.

**Comment by jtr13** [comment]
This is the same problem as described here https://github.com/jtr13/cc21fall2/issues/166

**Comment by nicric99** [comment]
So I just require to put an eval false in the chunk? However there are no run chunks in the rmd files, it is just a link to the resource pdf (cheatsheet). What should I do then? Thank you

**Comment by jtr13** [comment]
It's still failing from the merge before the one you did, not yours. I'm working on fixing it. You can tell from the error message where the problem is:
`Failed to compile running_sql_queries_on_dataframes.Rmd`

**Comment by jtr13** [comment]
It's working now: https://github.com/jtr13/cc21fall2/actions/runs/1455503441
