### ISSUE TITLE
Issue on bookdown

### ISSUE THREAD

**Issue by alexnsaunders** [jtr13/cc21fall2#169]
I see an issue on the bookdown run - it appears to be emanating from dataframe_operation_tutorial.Rmd. Possibly b/c the resources folder is not correctly tagged (it has a different name) or the path is wrong. The weird thing is it seems the commit was 10 days ago, so presumably it was running for a while I cannot find the pull request or merge (or anything but the initial commit). Any ideas where to look? @jtr13

**Comment by jtr13** [comment]
Here's the merged PR: https://github.com/jtr13/cc21fall2/pull/48 It looks like a resource was referenced incorrectly. It is very weird that it didn't cause problems earlier!

**Comment by alexnsaunders** [comment]
Found it @sarthak-arora1997 Hi Sarthak, the push you did yesterday is causing issues with the bookdown, you can check it on the action tab. There was a small typo that I fixed but the other issue is the resources folder is not properly tagged.

Here is the section from the submission guide - can you request changes from the author or do it yourself - bear in mind the sample_project in this case the folder is actually named Rayzyz_resources I believe but check in the inital commit. Let me know if you need further assistance. Alex

6. [OPTIONAL] If you have other resources (such as images) included in your project, create a folder under `resources/`. In our example, it is [`resources/sample_project/`](resources/sample_project){target="_blank"}. Put the resources files there. Be sure to change all the links in your `.Rmd` to include `resources/.../`, for example:

**Comment by alexnsaunders** [comment]
> Here's the merged PR: #48 It looks like a resource was referenced incorrectly. It is very weird that it didn't cause problems earlier!

It would have! There was a typo in the filename, it was a commit one before mine, I fixed that but didn't notice the resources issue. Anyway I referred back to the merger - if there are problems or they need help I can probably fix tomorrow evening.

**Comment by jtr13** [comment]
Oh, that makes sense, though the typo in the filename should have caused a problem.

**Comment by alexnsaunders** [comment]
Maybe it was merged but not pushed until yesterday?! Very weird - I am learning a lot! The typo caused the initial problem for sure.

![image](https://user-images.githubusercontent.com/16513257/141714386-171f8791-daa3-4532-9d1b-fa0a2b510b37.png)

**Comment by jtr13** [comment]
Once it's merged it's part of the project and GitHub Actions starts running immediately. It may have to do with the fact that the typo was `.Rmd` instead of `.rmd`: some processes might recognize it as the same file while others don't.

**Comment by alexnsaunders** [comment]
@jtr13 Thanks for fixing, didn't get time to do y'day , same for originator I would guess. Closing issue.
