### ISSUE TITLE
Package "car" can't be loaded while it is already in description

### ISSUE THREAD

**Issue by pyropig** [jtr13/cc21fall2#175]
In recent compilings, the package "car" failed to be loaded while it is already in the description file.
https://github.com/jtr13/cc21fall2/actions/runs/1473408793

**Comment by jtr13** [comment]
Thanks for the heads-up!

**Comment by alexnsaunders** [comment]
Do you think it could be because of the libPaths command before? Try taking that out. It probably refers to the writers C:/ drive.
Also there appears to be this anova_revised and the original anova.Rmd by same author.  We could check both aren’t getting rendered. @pyropig

**Comment by jtr13** [comment]
That line is commented out so I don't think that's it. The `car` package is being installed (see: https://github.com/jtr13/cc21fall2/runs/4245347111?check_suite_focus=true#step:5:220) but not clear why it's not being found.

**Comment by jtr13** [comment]
Oh, never mind, I see you're the one who added the comment!

**Comment by alexnsaunders** [comment]
@AdrianGarciaH Hi Adrian - tagging you on the issue - we found the car package was ok it was the .LibPath but we won't be able to run the bookdown until we get the crop.csv file submitted in the correct directory /resources/anova_revised or whatever.. I commented on the PR - apologies for the double-tag!! 😃 
Weirdly it did work at some point https://jtr13.github.io/cc21fall2/anova-tutorial.html but as you can see it's just a litany of errors as the code didn't run correctly.

**Comment by AdrianGarciaH** [comment]
Thank you @alexnsaunders !

**Comment by jtr13** [comment]
Can this be closed since the **car** package wasn't the problem?

**Comment by alexnsaunders** [comment]
Closed as we fixed the package issue.
