### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Tylermarshall21** [jtr13/cc21fall2#177]
@jtr13  This build failed: https://github.com/jtr13/cc21fall2/actions/runs/1474794749
I think it failed due to an earlier issue and not the PR I just merged, but I'm not sure

**Comment by alexnsaunders** [comment]
Yes, you are right. Not to do with the PR you merged. We won't be able to tell if this PR is causing a problem until the first issue is fixed which needs some work on the submission, but thanks. I'll close this issue we can always revist. Hopefully we won't need to!
