### ISSUE TITLE
rmd file tried to open non-exist file in root directory

### ISSUE THREAD

**Issue by pyropig** [jtr13/cc21fall2#178]
Recent render fails on anova_tutorial_revised.Rmd, who tried to open file crop.data.csv under root directory. There's no such file in the root or in the resource folder, thus I believe we need either change all his code to eval=FALSE (his code rely on data on this file), or we can ask them to add this resource file in the resource folder and edit the open code.
see link here: https://github.com/jtr13/cc21fall2/actions/runs/1474794749

**Comment by jtr13** [comment]
Another option is to comment out the `.Rmd` from the `_bookdown.yml` file while we wait. I think it's important to get the build running so we can detect other problems and not be stuck on this one.

**Comment by alexnsaunders** [comment]
Moved to #179
