### ISSUE TITLE
Error in file(file, "rt") : cannot open the connection

### ISSUE THREAD

**Issue by AdrianGarciaH** [jtr13/cc21fall2#179]
I'm not sure i understand enough to address this issue!
https://github.com/jtr13/cc21fall2/runs/4257535752?check_suite_focus=true

**Comment by alexnsaunders** [comment]
I think I commented on your pull request but you just have to ask the submitter to resubmit with the correct files named in the correct directory. 

https://jtr13.github.io/cc21fall2/github-submission-instructions.html

In particular this part! 
[OPTIONAL] If you have other resources (such as images) included in your project, create a folder under resources/. In our example, it is resources/sample_project/. Put the resources files there. Be sure to change all the links in your .Rmd to include resources/.../, for example:

![Test Photo](resources/sample_project/pumpkins.jpg)


Don't worry about the issue and the error - we can take care of easily and it looks more intimidating then it is! Essentially their code tries to load a spreadsheet - but they didn't submit the spreadsheet so when it runs in Github it can't find it! But I can take care of that part! You just need them to resubmit with the file (and preferably deleting the .Lib(C: reference too)

**Comment by alexnsaunders** [comment]
This one looks like Professor Robbins merged (anova). Still commented out in _bookdown I'll take off tomorrow. Trying to install Python on the actions file - fingers crossed. We're working again though.

**Comment by jtr13** [comment]
Fingers crossed. It might involve more than just getting Python installed but making sure that the reticulate package finds it. I would look for examples of bookdown + GitHub Actions + Python.

**Comment by alexnsaunders** [comment]
Closing this one for now. Separately, Python is installed, I believe, but requirements for packages and potentially making sure reticulate finds need to be solved. Might be too challenging given the size of our commits.
