### ISSUE TITLE
Error in bookdown

### ISSUE THREAD

**Issue by Abhimanyu210100** [jtr13/cc21fall2#180]
I compiled a few more PRs today and noticed that the bookdown is facing some errors in building the site. The error seems to be coming from a file compiled by someone else because I haven't merged the 'mongodb_and_r.Rmd'. I am not sure who to reach out to for this

https://github.com/jtr13/cc21fall2/runs/4290627505?check_suite_focus=true

**Comment by alexnsaunders** [comment]
Ok thanks. I’m not sure what is going on with this as I set eval to false but don’t worry. I’ll look into. @jtr13 any idea why the eval is not working? It worked last night!

**Comment by jtr13** [comment]
Will take a look tonight... thanks for the heads-up!

**Comment by jtr13** [comment]
I fixed this one by adding `cache=FALSE` to the setup chunk in which you set `eval=FALSE`. What seems to be happening is that a cached version of the setup chunk is coming back in which `eval` is not set to `FALSE` and therefore it tries to execute lines 63-65 `mongodb_and_r.Rmd`.  It's not clear why this is happening but cache behavior is really hard to understand. There's another problem now... let me know if you want to have a go at it.

**Comment by pyropig** [comment]
The most recent run seems broke on a call to import "matplotlib" (isn't this a python library?) which we don't have in the DESCRIPTION file. A guess is to add this package may fix the issue.

**Comment by jtr13** [comment]
We don't have it set up to work with Python so unfortunately we'll need to set Python chunks to `eval=FALSE` unless someone wants to tackle this issue. See: https://github.com/jtr13/cc21fall2/issues/157

**Comment by alexnsaunders** [comment]
Closing this as resolved - leaving #157 open.
