### ISSUE TITLE
Issue in use_python_in_r.Rmd

### ISSUE THREAD

**Issue by Gangadharareddy514** [jtr13/cc21fall2#184]
Hi Professor @jtr13,

I missed out on this, other files are done. Last time for a RMD file I forgot to update it in the bookdown.yml and merged the file, I had asked you on what can be done, you suggested me to update the bookdown.yml on the main bookdown. But I forgot doing that, now I have updated in bookdown file, I am getting the following error, could you please help me out.

https://github.com/jtr13/cc21fall2/actions/runs/1517467763
Error: Process completed with exit code 1.

**Comment by alexnsaunders** [comment]
Ok thanks. We dont have Python installed. You can set eval and cache to False or if you don’t know how I’ll take care of it tonight. Alex

**Comment by Gangadharareddy514** [comment]
@alexnsaunders Thank you so much for the reply. It would be great if you could take care of it.

**Comment by alexnsaunders** [comment]
I did! Closed.

**Comment by Gangadharareddy514** [comment]
Good Job @alexnsaunders. Thanks for closing the issue.
