### ISSUE TITLE
Failing on dependencies

### ISSUE THREAD

**Issue by alexnsaunders** [jtr13/cc21fall2#186]
I'm a bit at a loss why we're failing now - I pushed a new request through that just fixed some typos - seems to be a problem with the dependencies but v. difficult to diagnose. Looks like there is a page error somewhere but not sure how to track down. Not sure what the fix is without just going through and trying to find if it is a specific package in question (could also be a remote system issue I guess). Very speculative from me unfort.

**Comment by jtr13** [comment]
Re: https://github.com/jtr13/cc21fall2/runs/4390551492
I'm quite sure this failure was beyond our control; this seems to have been the issue: https://github.com/r-lib/actions/issues/447
